@api = http://localhost:3000
@accountId = 6645b7dba0039dc3ba28543f

### List accounts

GET {{api}}/
Accept: application/json

### Create a new account

POST {{api}}/accounts
Accept: application/json
Content-Type: application/json

{
  "owner": "Jérémy Sorant"
}

### Get an account's balance

GET {{api}}/accounts/{{accountId}}
Accept: application/json
Content-Type: application/json

### Get an account's balance in JPY currency

GET {{api}}/accounts/{{accountId}}
Accept: application/json
Content-Type: application/json

{
  "currency": "JPY"
}

### Deposit money into an account

POST {{api}}/accounts/{{accountId}}/deposit
Accept: application/json
Content-Type: application/json

{
  "amount": "1.50"
}

### Withdraw money from an account

POST {{api}}/accounts/{{accountId}}/withdraw
Accept: application/json
Content-Type: application/json

{
  "amount": "1.15"
}

