@api = http://localhost:3000
@walletId = 6632849ac8753a10d8de26a1

### List wallets

GET {{api}}/
Accept: application/json

### Create a new wallet

POST {{api}}/wallets
Accept: application/json
Content-Type: application/json

{
  "owner": "Jérémy Sorant"
}

### Get a wallet

GET {{api}}/wallets/{{walletId}}
Accept: application/json
Content-Type: application/json

### Get a wallet in JPY currency

GET {{api}}/wallets/{{walletId}}
Accept: application/json
Content-Type: application/json

{
  "currency": "JPY"
}

### Add money into wallet

POST {{api}}/wallets/{{walletId}}/add
Accept: application/json
Content-Type: application/json

{
  "amount": "1.50"
}

### Remove money from wallet

POST {{api}}/wallets/{{walletId}}/remove
Accept: application/json
Content-Type: application/json

{
  "amount": "1.15"
}

